app:
  name: "SignLanguageTranslator"
  version: "1.0.0"
  environment: "production"
  debug: false

languages:
  sign_languages:
    - code: "ASL"
      name: "American Sign Language"
      model_path: "models/asl_v1.0.h5"
      vocabulary_size: 1000
      regions: ["US", "CA"]
    
    - code: "BSL"
      name: "British Sign Language"
      model_path: "models/bsl_v1.0.h5"
      vocabulary_size: 800
      regions: ["GB", "AU"]
    
    - code: "JSL"
      name: "Japanese Sign Language"
      model_path: "models/jsl_v1.0.h5"
      vocabulary_size: 1200
      regions: ["JP"]
    
    - code: "CSL"
      name: "Chinese Sign Language"
      model_path: "models/csl_v1.0.h5"
      vocabulary_size: 1500
      regions: ["CN", "HK", "TW"]
  
  spoken_languages:
    - "en"
    - "es"
    - "fr"
    - "de"
    - "ja"
    - "zh"
    - "ko"
    - "pt"
    - "ru"
    - "ar"

models:
  detection:
    confidence_threshold: 0.8
    max_hands: 2
    model_complexity: 1
    smooth_landmarks: true
    
  recognition:
    architecture: "transformer"
    embedding_dim: 256
    num_heads: 8
    num_layers: 6
    dropout_rate: 0.1
    max_sequence_length: 100
    
  translation:
    service: "google_translate"
    backup_service: "azure_translator"
    cache_enabled: true
    cache_ttl: 3600

data:
  preprocessing:
    image_size: [224, 224]
    normalization: "standardize"
    augmentation:
      rotation_range: 15
      zoom_range: 0.2
      horizontal_flip: false
      brightness_range: [0.8, 1.2]
      
  collection:
    min_confidence: 0.7
    save_anonymous: true
    consent_required: true
    retention_days: 90

api:
  host: "0.0.0.0"
  port: 8080
  cors_origins: ["*"]
  rate_limit:
    requests_per_minute: 60
    requests_per_day: 10000
  authentication:
    enabled: true
    jwt_secret: "${JWT_SECRET}"
    token_expiry: 3600

monitoring:
  metrics:
    enabled: true
    export_interval: 60
    backends:
      - "prometheus"
      - "cloudwatch"
  
  logging:
    level: "INFO"
    format: "json"
    outputs:
      - "stdout"
      - "file"
      - "cloudwatch"
    
  tracing:
    enabled: true
    sample_rate: 0.1
    backend: "jaeger"

deployment:
  auto_scaling:
    min_instances: 2
    max_instances: 10
    target_cpu: 70
    target_memory: 80
    
  health_check:
    endpoint: "/health"
    interval: 30
    timeout: 5
    
  model_serving:
    backend: "tensorflow_serving"
    batch_size: 32
    timeout: 1000